{
 "title": "ping_monitor Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server down status?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ping_up", "legendFormat": "{{destination}}" }
   ]
  },
  {
   "title": "Average RTT Ping (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "ping_rtt_avg_ms", "legendFormat": "{{destination}} " }
   ]
  },
  {
   "title": "Ping RTT Max/Min (ms)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ping_rtt_max_ms", "legendFormat": "    {{destination}} - Max" },
    { "expr": "ping_rtt_max_ms", "legendFormat": "    {{destination}} - Min" }
   ]
  },
  {
   "title": "Average RTT (ms)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ping_rtt_avg_ms", "legendFormat": "{{destination}}" }
   ]
  }
 ]
}